### ISSUE TITLE
git clone 후 class path 오류

### ISSUE THREAD

**Issue by jieun1127** [YooDonggyu/hue#7]
전
`<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7">
`
 후
`<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER">`

**Comment by jieun1127** [comment]
java build path 경로를 직접 지정해주어야 한다.

"깃클론폴더명/Hue/src"

**Comment by yunheenet** [comment]
JAVA단은 위 처럼 'java build path'경로를 직접 지정해 주니까 빌드가 되었지만

WEB_CONTENT에서 jsp를 실행시키려고 했을때 다시 경로 오류가 발생했음.

궁극적으로는 이클립스에서 git clone을 할 때 제대로 된 설정으로 해주어야 함.
